const data={
    title:"pizza hut",
    imageUrl:"",
    foods:[
        {
        dishName:"chicken pizza",
        dishPic:"",
        price:5,
        },
    ],
    time:"9am to 9pm",
    pickup:true,
    delivery:true,
    isOpen:true,
    logoUrl:"",
    rating:5,
    ratingCount:"5",
    code:"1234",
    coords:{
        id:"123456",
        latitude:"1234",
        latitudeDelta:"1234",
        longitude:"1234",
        longitudeDelta:"1234",
        address:"Gurugram India",
    },
    title:"Burger King",
    imageUrl:"",
    foods:[{
        dishName:"chicken burger",
        price:2,
        dishPic:"",

        },
    ],
    time:"10am to 9pm",
    pickup:true,
    delivery:false,
    isOpen:true,
    logoUrl:"",
    rating:5,
    ratingCount:"5",
    code:"1234",
    coords:{
        id:"1234567",
        latitude:"1234",
        latitudeDelta:"1234",
        longitude:"1234",
        longitudeDelta:"1234",
        address:"Gurugram India",
    },
}